version: '3.3'
services:
  php-apache-environment:
    container_name: akashphp1
    build: .
    image: kk
    volumes:
      - ./:/var/www/html/
    environment:
        MYSQL_ROOT_PASSWORD: q1234
        MYSQL_DATABASE: login
        MYSQL_USER: akash
        MYSQL_PASSWORD: q1234
    ports:
      - 1122:80
  datadb:
    container_name: db
    image: mysql
    volumes:
     - ./sql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: q1234
        MYSQL_DATABASE: login
        MYSQL_USER: akash
        MYSQL_PASSWORD: q1234
    ports:
        - "3344:3306"